### ISSUE TITLE
Data store

### ISSUE THREAD

**Issue by eloyesp** [Altoros/hacker-assessor#19]
We need to add a database to the mix, I was thinking on PostgreSQL (as it is already in heroku) but it could be great to make it work with SQLite in development (as it is better for development).

May be there are better options to keep the data, but this sounds pretty standard.

- [x] 1 -Create a new branch named *19-anydb*.
- [x] 2 - Assemble a script that creates a sqlite database and a seniorities table with rows *id*, *name* and *skills*.
- [x] 3 -  Assemble a script that loads ```./seniorities.json``` inside the newly created sqlite seniorities table.
- [x] 4 - Modify lines https://github.com/Altoros/hacker-assessor/blob/master/server.js#L19 and similar to call a findSeniority(‘sth’) function preserving current functionality. The function findSeniority should be something like ```require(‘**seniorities.js’).findSeniority```. This should be the last change in the ```./server.js``` of this branch.
- [x] 5 - Modify the function findSeniority from step 4 to make it search inside the sqlite database.
- [x] 6 - Make sure things work the same way it worked before.

**Comment by n370** [comment]
- [ ] 1 - crear una rama "19-anydb”.
- [ ] 2 - modificar las lineas  https://github.com/Altoros/hacker-assessor/blob/master/server.js#L19 y similares por llamadas a función una findSeniority('algo') que mantenga la funcionalidad.  la función findSeniority debería ser un `require('seniorities.js').findSeniority` es sumamente importante que sea la última modificación en esta rama del ‘server.js'.
- [ ] 3 - hacer un script js que cree una db sqlite  y una tabla seniority con atributos ( id , name , skills ).
- [ ]  4 - hacer un script que cargue los seniorities que tenemos en el json en la tabla.
- [ ]  5 - modificar la función findSeniority del punto 2 para que busque en la base de datos.
- [ ]  6 - ver que la funcionalidad sigue intacta.

**Comment by n370** [comment]
- [x] 1 -Create a new branch named "19-anydb”.
- [] 2 - Modify lines https://github.com/Altoros/hacker-assessor/blob/master/server.js#L19 and similar to call a findSeniority(‘sth’) function preserving current functionality. The function findSeniority should be something like ```require(‘**seniorities.js’).findSeniority```. This should be the last change in the ```./server.js``` of this branch.
- [] 3 - Assemble a script that creates a sqlite database and a seniorities table with rows *id*, *name* and *skills*.
- [] 4 -  Assemble a script that loads ```./seniorities.json``` inside the newly created sqlite seniorities table.
- [] 5 - Modify the function findSeniority from step 2 to make it search inside the sqlite database.
- [] 6 - Make sure things work the same way it worked before.

**Comment by n370** [comment]
@eloyesp Do you think is a good idea to use https://www.npmjs.com/package/any-db-migrate for completing steps 2 and 3. http://www.spritecloud.com/2014/04/node-js-database-migration/

**Comment by n370** [comment]
I guess I already know your answer but it doesn’t hurt to ask.

**Comment by n370** [comment]
Ready to review @eloyesp
