### ISSUE TITLE
Debería haber dos seniorities distintos.

### ISSUE THREAD

**Issue by eloyesp** [Altoros/hacker-assessor#6]
Actualmente, el único seniority que funciona es Senior FrontEnd developer, deberíamos agregar el de Senior FullStackJS, de forma similar al de frontend.

Idealmente, debería haber algunas coincidencias entre ambos seniorities, pero el fullstack requiere Node, mientras que frontend no. De esta forma vamos a poder ejercitar el código de la aplicación, teniendo distintas recomendaciones para cada seniority.

**Comment by mgarciap** [comment]
KISS
