### ISSUE TITLE
Invite a hacker

### ISSUE THREAD

**Issue by lcostantini** [Altoros/hacker-assessor#60]
Creating new hackers is by invitation so you need to be logged in and then invite(create) a new hacker.
You can select his career and seniority and automatically be added the acquirements for the new hacker.

**Comment by mgarciap** [comment]
WAT? I am not sure this is on the BackLog. Hacker should be created by an administrator (it initially be HR, in this case: me). There is no need to add complexity at this moment. Let's keep it extremelly simple
