### ISSUE TITLE
Agregar datos complementarios en skills

### ISSUE THREAD

**Issue by eloyesp** [Altoros/hacker-assessor#7]
Completar las descripciones y los recursos de las skills que se utilizan.

Además, habría que agregar un fallback para el caso en que un skill carece de información, para que la página no explote en ese caso.

**Comment by n370** [comment]
aa2bbb783

Creo que del lado del template o del server se podría agregar un if..else to test if a skill property exists.

**Comment by n370** [comment]
Completo las descripciones no más y dejamos el fallback para otra tarea?

**Comment by eloyesp** [comment]
No, please do both. The fallback is important as it make the server blow up, an `if (skill === undefined)` should make the trick.

**Comment by n370** [comment]
@eloyesp can you give an example? A stack trace of the blown up server on your local environment works. I can’t see this error happening with the code we have now.

**Comment by eloyesp** [comment]
@n370 sure, here it is: https://asciinema.org/a/8zx4ispm2vpocbimkppff6hky

**Comment by n370** [comment]
Thanks! Great feedback @eloyesp. In a moment I'll push the changes in another branch and open a PR for you to checkout and review.
